package de.shanox.android.lifecalendar.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006e10)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF71ff75)
val md_theme_light_onPrimaryContainer = Color(0xFF002201)
val md_theme_light_secondary = Color(0xFF53634e)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd6e8ce)
val md_theme_light_onSecondaryContainer = Color(0xFF111f0f)
val md_theme_light_tertiary = Color(0xFF386569)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbcebf0)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfdf6)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfdf6)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdee4d8)
val md_theme_light_onSurfaceVariant = Color(0xFF42493f)
val md_theme_light_outline = Color(0xFF73796f)
val md_theme_light_inverseOnSurface = Color(0xFFf1f1eb)
val md_theme_light_inverseSurface = Color(0xFF2f312d)
val md_theme_light_inversePrimary = Color(0xFF00e632)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF00e632)
val md_theme_dark_onPrimary = Color(0xFF003a04)
val md_theme_dark_primaryContainer = Color(0xFF005309)
val md_theme_dark_onPrimaryContainer = Color(0xFF71ff75)
val md_theme_dark_secondary = Color(0xFFbacbb3)
val md_theme_dark_onSecondary = Color(0xFF253422)
val md_theme_dark_secondaryContainer = Color(0xFF3c4b38)
val md_theme_dark_onSecondaryContainer = Color(0xFFd6e8ce)
val md_theme_dark_tertiary = Color(0xFFa0cfd4)
val md_theme_dark_onTertiary = Color(0xFF00363a)
val md_theme_dark_tertiaryContainer = Color(0xFF1e4d51)
val md_theme_dark_onTertiaryContainer = Color(0xFFbcebf0)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3dd)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3dd)
val md_theme_dark_surfaceVariant = Color(0xFF42493f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c8bc)
val md_theme_dark_outline = Color(0xFF8c9288)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dd)
val md_theme_dark_inversePrimary = Color(0xFF006e10)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF24ff48)
val error = Color(0xFFba1b1b)